name: Update Submodules

on:
  schedule:
    - cron: '0 4 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config core.autocrlf false

      - name: Update submodules
        run: |
          # Ensure submodules are initialized
          git submodule init
          # Attempt to update submodules, continue even if some fail
          git submodule update --remote --merge || echo "Submodule update failed, proceeding..."
          git add .

      - name: Download Moodle version file
        run: |
          for i in {1..3}; do
            wget -q https://raw.githubusercontent.com/moodle/moodle/MOODLE_500_STABLE/version.php -O version.php && break
            echo "Download failed, retrying ($i/3)..."
            sleep 5
          done
          if [ ! -s version.php ]; then
            echo "Failed to download Moodle version file after 3 attempts"
            exit 1
          fi
        shell: bash

      - name: Check for changes
        id: check_changes
        run: |
          git status
          if git diff --quiet; then
            echo "No changes in submodules"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in submodules"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -am "Update submodules to latest"
          git push origin main
